### ISSUE TITLE
Отсутствует пакет ForeCA

### ISSUE THREAD

**Issue by mindw00rk** [ranalytics/tsa-r#1]
В разделе 5.2 книги: 

`cryptos %>% features(., y, list(coef_hurst, feat_spectral))`

RStudio выдает:

> cryptos %>% features(., y, list(coef_hurst, feat_spectral))
> # A tibble: 22 x 2
>    coin      coef_hurst
>    <chr>          <dbl>
>  1 augur           1.00
>  2 bitcoin         1.00
>  3 cardano         1.00
>  4 chainlink       1.00
>  5 dash            1.00
>  6 decred          1.00
>  7 dogecoin        1.00
>  8 eos             1.00
>  9 ethereum        1.00
> 10 iota            1.00
> # ... with 12 more rows
> Предупреждение:
> 22 errors (1 unique) encountered for feature 2
> [22] The `ForeCA` package must be installed to use this functionality. It can be installed with install.packages("ForeCA")

**Comment by ranalytics** [comment]
Спасибо, я добавил ForeCA в скрипт для установки пакетов
